### ISSUE TITLE
Does this still build?

### ISSUE THREAD

**Issue by chagai95** [reinkepatrick/webrtc-client#2]
I found your questions here, https://react-native-webrtc.discourse.group/t/webrtc-does-not-work-for-me/387
I just wanted to check your project out, if it still works... there is no readme or anything else...

**Comment by reinkepatrick** [comment]
Theoretically it should still work, but has not been actively tested. Normally it should be the port and IP address changed, then built and executed.

**Comment by chagai95** [comment]
thanks for answering so fast! you mean you never built and ran it yourself?

**Comment by reinkepatrick** [comment]
I did but its kinda long ago and only for testing purposes

**Comment by chagai95** [comment]
could you help me out and tell me which versions you used?
	1. Java sdk
	2. gradle version(com.android.tools.build AND distributionUrl)
	3. compileSdkVersion(what is that?)
	4. buildToolsVersion(what is that?)
	5. react native versions (react native and react native cli )
	6. All the apple stuff I never touched versions.
        7. multiDexEnabled ?

**Comment by reinkepatrick** [comment]
I cant tell you nothing about that, I dont have the used system anymore
